image: alpine

before_script:
   - apt-get update -qq && apt-get install -y sqlite3 python3 python3-dev python3-pip
   - pip3 install django==2.1.8

job1:
   - python3 manage.py runserver 0.0.0.0:8080