image: ubuntu

stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip sqlite3
  - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
  - python manage.py runserver 0.0.0.0:8087


























#before_script:
#  - apt-get update && apt-get install -y python3 git python-pip
#  - pip3 install django

#stages:
#  - install_deps
#  - build_prod
#  - deploy_prod
#
#cache:
#  key: ${CI_BUILD_REF_NAME}
#  paths:
#    - node_modules/
#    - dist
#
## 安装构建依赖
#install_deps_job:
#  stage: install_deps
#  only:
#    - master
#  script:
#    - python3 -V
#    - uname -a
#    - echo '安装构建依赖阶段'
#  tags:
#    - first-tag
#
## 打包新文件
#build_prod_job:
#  stage: build_prod
#  only:
#    - master
#  script:
#    - echo '打包新文件阶段'
#  tags:
#    - first-tag
#
## 登录项目部署服务器，移除旧版本项目文件，最后将打包好的文件拷贝过去
#deploy_prod_job:
#  stage: deploy_prod
#  only:
#    - master
#  script:
#    - echo '登录项目部署服务器，移除旧版本项目文件，最后将打包好的文件拷贝过去'
#  tags:
#    - first-tag
